# Generated by Django 4.1.4 on 2023-01-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diseases_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=50)),
                ('Patient_Age', models.IntegerField()),
                ('Patient_Phone', models.BigIntegerField()),
                ('Patient_City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.city')),
                ('Patient_Diseases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.diseases')),
            ],
        ),
    ]
